
#SERVER
SERVER_PORT: 8081
ACTIVE_PROFILE: prod

#EMAIL CONFIG
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: sidofdountio406@gmail.com
EMAIL_PASSWORD:
VERIFY_EMAIL_HOST: http:/localhost${SERVER_PORT}